# Generated by Django 4.2.3 on 2023-07-26 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0003_booktype_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='username',
        ),
    ]
