# Generated by Django 4.2.3 on 2023-08-05 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0011_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorials',
            name='category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='quickstart.category'),
        ),
        migrations.AlterField(
            model_name='tutorials',
            name='heading',
            field=models.CharField(blank=True, max_length=100, verbose_name='Display Breadcrumb Page Title'),
        ),
        migrations.AlterField(
            model_name='tutorials',
            name='keywords',
            field=models.CharField(blank=True, max_length=200, verbose_name='Meta Keywords'),
        ),
        migrations.AlterField(
            model_name='tutorials',
            name='meta_tags',
            field=models.CharField(blank=True, max_length=200, verbose_name='Other Users Generated Tags for Search'),
        ),
    ]
