# Generated by Django 4.2.3 on 2023-08-05 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0012_alter_tutorials_category_alter_tutorials_heading_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorials',
            name='category',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='quickstart.category'),
        ),
    ]
